version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  backend:
    build: ./backend
    container_name: flashcards-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ELASTIC_URI=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  frontend:
    build: ./frontend
    container_name: flashcards-ui
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  esdata:
