version: '3.8'
services:
  backend:
    build: ./python_backend
    container_name: flashcards-python-api
    env_file:
      - ./python_backend/.env.production
    ports:
      - "5000:80"
    depends_on:
      - qdrant
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  frontend:
    build:
      context: ./frontend/flashcards-ui
      dockerfile: Dockerfile
    container_name: flashcards-ui
    ports:
      - "4200:80"
    depends_on:
      - backend


volumes:
  qdrant_data:
