version: '3.8'
services:
  backend:
    build: ./backend
    container_name: flashcards-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Storage__Provider=Qdrant
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6334
      - OpenAI__ApiKey=${OPENAI_API_KEY}
    depends_on:
      - qdrant
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
  frontend:
    build:
      context: ./frontend/flashcards-ui
      dockerfile: Dockerfile
    container_name: flashcards-ui
    ports:
      - "4200:80"
    depends_on:
      - backend
